name: Android Only Test CI/CD

on:
  push:
    branches: [ "test/*" ]

jobs:
  build:

    runs-on: self-hosted
    strategy:
      max-parallel: 4
      matrix:
        task:
          - bundleGoogleDistributionRelease
#          - assembleSamsungDistributionRelease
#          - assembleOnestoreDistributionRelease

    steps:
      - uses: actions/checkout@v4

      - name: Record Start Time
        id: start_time
        run: echo "workflow_start_time=$(date +%s)" >> $GITHUB_ENV

      - name: Set Build Number
        id: set_build_number
        run: echo "BUILD_NUMBER=${{ github.run_number }}" >> $GITHUB_ENV

      - name: Set up JDK 17
        uses: actions/setup-java@v3
        with:
          java-version: '17'
          distribution: 'temurin'
          cache: gradle

      - name: Set up Android SDK
        run: |
          ANDROID_HOME="${{ runner.temp }}/android-sdk"
          ANDROID_SDK_ROOT="${{ runner.temp }}/android-sdk"
          echo "ANDROID_HOME=$ANDROID_HOME" >> $GITHUB_ENV
          echo "ANDROID_SDK_ROOT=$ANDROID_SDK_ROOT" >> $GITHUB_ENV
          mkdir -p $ANDROID_HOME/cmdline-tools/latest
          curl -L https://dl.google.com/android/repository/commandlinetools-linux-7583922_latest.zip -o $ANDROID_HOME/cmdline-tools/latest/cmdline-tools.zip
          unzip $ANDROID_HOME/cmdline-tools/latest/cmdline-tools.zip -d $ANDROID_HOME/cmdline-tools/latest
          mv $ANDROID_HOME/cmdline-tools/latest/cmdline-tools/* $ANDROID_HOME/cmdline-tools/latest/
          rmdir $ANDROID_HOME/cmdline-tools/latest/cmdline-tools
          echo "$ANDROID_HOME/cmdline-tools/latest/bin" >> $GITHUB_PATH

      - name: Install Android SDK
        run: |
          yes | $ANDROID_HOME/cmdline-tools/latest/bin/sdkmanager --licenses
          $ANDROID_HOME/cmdline-tools/latest/bin/sdkmanager "platform-tools" "platforms;android-30" "build-tools;30.0.3"

      - name: Cache Gradle
        uses: actions/cache@v3
        with:
          path: |
            ~/.gradle/caches
            ~/.gradle/wrapper
          key: ${{ runner.os }}-gradle-${{ hashFiles('**/*.gradle*', '**/gradle-wrapper.properties') }}
          restore-keys: |
            ${{ runner.os }}-gradle-

      - name: Grant Execute Permission For Gradlew
        run: chmod +x gradlew

      - name: Sign AAB
        id: sign
        uses: r0adkll/sign-android-release@v1
        with:
            releaseDirectory: build/app/outputs/bundle/devRelease
            signingKeyBase64: ${{ secrets.ANDROID_KEYSTORE_JKS }}
            alias: ${{ secrets.ANDROID_KEY_ALIAS }}
            keyStorePassword: ${{ secrets.ANDROID_KEYSTORE_PASSWORD }}
            keyPassword: ${{ secrets.ANDROID_KEY_PASSWORD }}

      - name: Find APK
        id: find_apk
        run: |
          BUILD_NUMBER=${{ env.BUILD_NUMBER }}
          if [[ "${{ matrix.task }}" == "bundleGoogleDistributionRelease" ]]; then
            APK_NAME="app-google-distribution-release-${BUILD_NUMBER}.aab"
            APK_PATH=$(find app/build/app/outputs/bundle/ -name "app-google-distribution-release.aab" | head -n 1)
#          elif [[ "${{ matrix.task }}" == "assembleGoogleSandboxRelease" ]]; then
#            APK_NAME="app-google-sandbox-release-${BUILD_NUMBER}.apk"
#            APK_PATH=$(find app/build/outputs/apk/ -name "app-google-sandbox-release.apk" | head -n 1)
#          fi
          if [ -z "$APK_PATH" ]; then
            echo "No APK file found for ${{ matrix.task }}"
            exit 1
          fi
          NEW_APK_PATH="${APK_PATH%/*}/$APK_NAME"
          mv $APK_PATH $NEW_APK_PATH
          echo "APK_PATH=$NEW_APK_PATH" >> $GITHUB_ENV
          echo "APK_NAME=$APK_NAME" >> $GITHUB_ENV

      - name: Upload APK
        uses: actions/upload-artifact@v4
        with:
          name: ${{ env.APK_NAME }}
          path: ${{ env.APK_PATH }}
          retention-days: 3

      - name: Record End time
        id: end_time
        run: echo "workflow_end_time=$(date +%s)" >> $GITHUB_ENV

      - name: Calculate Total Duration
        id: total_duration
        run: |
          workflow_start_time=${{ env.workflow_start_time }}
          workflow_end_time=${{ env.workflow_end_time }}
          total_duration=$((workflow_end_time - workflow_start_time))
          if [ $total_duration -lt 60 ]; then
            total_duration_formatted="${total_duration}초"
          else
            total_minutes=$((total_duration / 60))
            total_seconds=$((total_duration % 60))
            total_duration_formatted="${total_minutes}분 ${total_seconds}초"
          fi
          echo "Total duration: $total_duration_formatted"
          echo "total_duration_formatted=$total_duration_formatted" >> $GITHUB_ENV

      - name: Send Build Status Slack Msg
        uses: 8398a7/action-slack@v3
        env:
          SLACK_WEBHOOK_URL: ${{ secrets.SLACK_PERSONAL_WEB_HOOK_URL }}
        with:
          status: custom
          custom_payload: |
            {
             "attachments": [
               {
                 "color": "${{ job.status == 'success' && '#36a64f' || '#FF0000' }}",
                 "title": "GitAction 알림",
                 "fields": [
                {
                  "title": "WorkFlows",
                  "value": "*${{ github.workflow }}*",
                  "short": true
                  },
                  {
                  "title": "Repo",
                  "value": "<https://github.com/${{ github.repository }}>",
                  "short": false
                  },
                  {
                  "title": "Action URL",
                  "value": "<https://github.com/${{ github.repository }}/actions/runs/${{ github.run_id }}>",
                  "short": false
                  },
                  {
                     "title": "Commit",
                     "value": "<https://github.com/${{ github.repository }}/commit/${{ github.sha }}|${{ github.sha }}>",
                     "short": false
                   },
                  {
                     "title": "Branch",
                     "value": "*${{ github.ref }}*",
                     "short": true
                   },
                   {
                     "title": "Event Name",
                     "value": "_${{github.event_name}}_",
                     "short": true
                   },
                   {
                     "title": "작성자",
                     "value": "*${{ github.event.head_commit.author.name }}*",
                     "short": true
                   },
                  {
                     "title": "빌드 시간",
                    "value": "${{ env.total_duration_formatted }}",
                     "short": true
                   },
                  {
                     "title": "Commit Message",
                     "value": "*${{github.event.head_commit.message}}*",
                     "short": false
                   },
                 ]
               }
             ]
            }
        if: always()

  cleanup:
    runs-on: ubuntu-latest
    needs: build
    steps:
      - name: Cleanup Artifacts
        run: |
          echo "Cleaning up old artifacts..."
          gh api repos/:owner/:repo/actions/artifacts | jq '.artifacts | sort_by(.created_at) | .[0:-50] | .[] | .id' | xargs -I {} gh api repos/:owner/:repo/actions/artifacts/{} -X DELETE
