name: Android Only Test CI/CD

on:
  push:
    branches: [ "test/*" ]

jobs:
  build:

    runs-on: ubuntu-latest

    steps:
      - uses: actions/checkout@v4

      - name: Set up JDK 17
        uses: actions/setup-java@v3
        with:
          java-version: '17'
          distribution: 'temurin'
          cache: gradle

      - name: Cache Gradle
        uses: actions/cache@v3
        with:
          path: |
            ~/.gradle/caches
            ~/.gradle/wrapper
          key: ${{ runner.os }}-gradle-${{ hashFiles('**/*.gradle*', '**/gradle-wrapper.properties') }}
          restore-keys: |
            ${{ runner.os }}-gradle-

      - name: Grant Execute Permission For Gradlew
        run: chmod +x gradlew

#      - name: Clean Gradle
#        run: ./gradlew clean

#      - name: Build Gradle
#        run: ./gradlew build

#      - name: Build Google Distribution Release Apk
#        run: ./gradlew assembleGoogleDistributionRelease --stacktrace
#
#      - name: Build Google Sandbox Release Apk
#        run: ./gradlew assembleGoogleSandboxRelease --stacktrace
#
#      - name: Build Samsung Distribution Release Apk
#        run: ./gradlew assembleSamsungDistributionRelease --stacktrace
#
#      - name: Build Samsung Sandbox Release Apk
#        run: ./gradlew assembleSamsungSandboxRelease --stacktrace
#
#      - name: Build OneStore Distribution Release Apk
#        run: ./gradlew assembleOnestoreDistributionRelease --stacktrace
#
#      - name: Build OneStore Sandbox Release Apk
#        run: ./gradlew assembleOnestoreSandboxRelease --stacktrace

      - name: Send Build Status Slack Msg
        uses: 8398a7/action-slack@v3
        with:
          status: custom
          custom_payload: |
            {
             "attachments": [
               {
                 "color": "${{ job.status == 'success' && '#36a64f' || '#FF0000' }}",
                 "title": "GitAction 알림",
                 "fields": [
                  {
                     "title": "repo",
                     "value": "<https://github.com/${{ github.repository }}|${{ github.repository }}>",
                     "short": true
                   },
                  {
                     "title": "빌드 시간",
                    "value": "${{ steps.calculate_time.outputs.elapsed_time }} seconds",
                     "short": true
                   },
                  {
                     "title": "Commit",
                     "value": "<https://github.com/${{ github.repository }}/commit/${{ github.sha }}|${{ github.sha }}>",
                     "short": false
                   },
                  {
                     "title": "Branch",
                     "value": "*${{ github.ref }}*",
                     "short": true
                   },
                   {
                     "title": "Event Name",
                     "value": "_${{github.event_name}}_",
                     "short": true
                   },
                   {
                     "title": "Commit Message",
                     "value": "*${{github.event.head_commit.message}}*",
                     "short": true
                   },
                   {
                     "title": "작성자",
                     "value": "''${{ github.event.head_commit.author.name }}''",
                     "short": true
                   }
                 ]
               }
             ]
            }
          author_name: Kuma
        env:
          SLACK_WEBHOOK_URL: ${{ secrets.SLACK_WEB_HOOK_URL_SECRET }}
        if: always()

