name: Android-release CI/CD

on:
  push:
    branches: [ "master","feature/**" ]
  pull_request:
    branches: [ "master","feature/**" ]

jobs:
  build:

    runs-on: ubuntu-latest

    steps:
      - uses: actions/checkout@v4

      - name: Set up JDK 17
        uses: actions/setup-java@v3
        with:
          java-version: '17'
          distribution: 'temurin'
          cache: gradle

      - name: Cache Gradle
        uses: actions/cache@v3
        with:
          path: |
            ~/.gradle/caches
            ~/.gradle/wrapper
          key: ${{ runner.os }}-gradle-${{ hashFiles('**/*.gradle*', '**/gradle-wrapper.properties') }}
          restore-keys: |
            ${{ runner.os }}-gradle-

      - name: Grant execute permission for gradlew
        run: chmod +x gradlew

      - name: Clean Gradle
        run: ./gradlew clean

#      - name: Build with Gradle
#        run: ./gradlew build

      - name: Test secret
        run: echo ${{ secrets.TEST_SECRET }}

      - name: Get Current Date
        id: date
        run: echo "::set-output name=date::$(date +'%Y-%m-%d')"

      - name: Build Google Distribution release Apk
        run: ./gradlew assembleGoogleDistributionRelease --stacktrace

      - name: Build Google Sandbox release Apk
        run: ./gradlew assembleGoogleSandboxRelease --stacktrace

      - name: action-slack
        uses: 8398a7/action-slack@v3
        with:
            status: ${{ job.status }}
            author_name: 빌드 알림
        env:
                SLACK_WEBHOOK_URL: ${{ secrets.SLACK_WEBHOOK_URL }}

#      - name: Send Build Status Slack Msg
#        uses: 8398a7/action-slack@v3
#        with:
#          status: ${{ job.status }}
#          fields: workflow,job,commit,repo,author,took,ref
#          author_name: Kuma
#        env:
#          SLACK_WEBHOOK_URL: ${{ secrets.SLACK_WEBHOOK_URL }}
#        if: always()
